### PR TITLE
Mdikan/add new onselect

### PR DESCRIPTION
**Pull request by mikedikan**

### CODE REVIEW

**Comment by bbaker6225** [comment]
https://stackoverflow.com/questions/43503964/onkeydown-event-not-working-on-divs-in-react

**Comment by mikedikan** [comment]
> https://stackoverflow.com/questions/43503964/onkeydown-event-not-working-on-divs-in-react

Tried the tabIndex="0" with no luck, thanks for the suggestion though

**Comment by dianakhuang** [comment]
This seems reasonable to me, but I'll leave it up to others to tell whether or not it's `react`-y enough.

**Comment by mikedikan** [comment]
yeah, i can get rid of the link

**Pull request merged**
